### PR TITLE
Bump version for publish

### PR DESCRIPTION
**Pull request by haltman-at**
This PR just bumps the version so we can do a publish with the recent changes (in particular @frangio's fix!).  Basically in asking for review on this I'm just saying, hey, this is a good time to do a publish, right? :)

...and then hopefully we should be able to leave this alone until Solidity 0.6.0 hits...

### CODE REVIEW

**Comment by frangio** [comment]
A release sounds good, but I'm not sure who has permissions to publish the package.

**Comment by haltman-at** [comment]
Fortunately, I already got those permissions earlier!  Just didn't have permission to commit until now.  :)

**Comment by haltman-at** [comment]
(So, to be clear, that's an approval then? :) )

**Comment by frangio** [comment]
Actually, the version in package-lock.json still needs to be updated. Consider using `npm version` for bumping since it takes care of that automatically.

**Comment by haltman-at** [comment]
I see, I was unaware, will do!

**Comment by haltman-at** [comment]
OK, lockfile is updated, merging!  Let's get this thing released! :)

**Pull request merged**
