### PR TITLE
Remove punctuation highlighting for causing problems

### PR DESCRIPTION
**Pull request by haltman-at**
Punctuation highlighting seems to be causing a number of problems, and just not working entirely consistently.  I don't have time to figure out a proper solution right now, so, I'm just going to remove it for now. :-/

### CODE REVIEW

**Comment by haltman-at** [comment]
Note, this does leave `:` and `?` in a kind of limbo.  I could leave in punctuation highlighting for those, but that seems like it would stand out in a bad way.

**Comment by haltman-at** [comment]
Sorry, I should explain just what problems this was causing.

The biggest was that assembly blocks weren't closing properly.  So after an assembly block, highlighting would be screwed up.

Also, less importantly, various punctuation that was supposed to get highlighted just didn't.

I don't have a full list of the problems because I don't quite understand what's going on here, but that's what I noticed.

**Review by cds-amal — APPROVED** [review]
Thanks @haltman-at. Looks good.

**Comment by haltman-at** [comment]
As an example, here's a problem caused by an assembly block not closing properly earlier:

Bad highlighting

**Comment by joshgoebel** [comment]
I don't understand which part of that is an "assembly block" though I can see where the highlighting looks strange.

**Comment by haltman-at** [comment]
Ah, sorry, none of that is.  The assembly block is earlier in the code and not displayed here; you're just seeing the results of it.

**Comment by joshgoebel** [comment]
Ah, it'd be helpful to see the whole context :)  Or at least the block + broken code.

**Comment by haltman-at** [comment]
Oh. Well, I don't have the whole thing readily to hand, but basically, earlier there was an `assembly { ... }` block.  In order to make these work, we do a bit of a trick where the assembly environment itself cannot end on its own, and its chiled, the environment for the actual *block*, ends its parent when it closes.  Anyway, somehow the fact that braces were now being highlighted caused the assembly environment to never actually end, and so we got assembly highlighting (instead of non-assembly highlighting) outside of the assembly block.

I can dig up more detail if you want, but as best I can tell that's roughly what happened.

**Pull request merged**
