### PR TITLE
Test and fix number boundary for non-Chrome browsers

### LINKED ISSUE #9: Negative lookbehind not supported in Firefox
This plugin is using negative lookbehind `(?<! ...)` which is not yet widely supported. In particular it [doesn't work in Firefox yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1225665), but also not in Safari or Edge as can be seen in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Browser_compatibility).

https://github.com/highlightjs/highlightjs-solidity/blob/3c0a75c7f075281b218f300331c18fd8fc076640/solidity.js#L133

### LINKED ISSUE #11: Test suite
This library needs a test suite so that we can feel more comfortable making changes without breaking things.

### PR DESCRIPTION
**Pull request by frangio**
Fixes #9. Fixes #11 (partially, this needs many more tests).

### CODE REVIEW

**Comment by haltman-at** [comment]
Hey, @pospi, @marcoscaceres, any chance this could get reviewed/merged anytime soon?

Btw, @frangio, slight mistake I just noticed looking at this myself: on line 205, you use the feature detection as a condition but the result doesn't depend on it... I'm assuming you meant to use the lookbehind when available?

**Comment by marcoscaceres** [comment]
This looks good to me. @pospi?

**Comment by frangio** [comment]
Good catch @haltman-at. Fixed it.

**Comment by haltman-at** [comment]
> This looks good to me. @pospi?

I mean, you're running this project now, right?  This doesn't really need any additional approval, right?

(...and, uh, could I get my PR that I have up looked at as well, if you don't mind...?)

**Comment by marcoscaceres** [comment]
To be clear, I’m not running the project. I just help at the organization level (I don’t actually know what this language is even used for 😊). However, we can always use more maintainers if you folks want to help out and keep things moving quickly.

**Comment by frangio** [comment]
Sure! I would be happy to help maintain and improve this project.

**Comment by haltman-at** [comment]
Yes, I would as well!

**Comment by marcoscaceres** [comment]
@frangio, @haltman-at, that's awesome to hear! Will add you!

**Comment by haltman-at** [comment]
So, uh, I guess since I can do this now, I'm just going to go ahead and merge this!

And then maybe we can release this pretty soon, just want to get my PR in as well and then maybe one other small thing. :)

**Pull request merged**
